<?php
    return [
        'slider_path' => 'slider',
        'dish_path' => 'dish',
        'home_port_count' => 0,
        'paginateMenuPage' => 9,
        'paginateProducts' => 8,
        'paginateBlog' => 10,
        'paginateCategoryAdmin' => 15,
        'paginateProductsAdmin' => 20,
        'paginateBlogAdmin' => 20,
        'emailContacts' => 'info@aurora-borealis.ru',
        'emailOrders' => 'info@aurora-borealis.ru',
        'img_width' => 400,
        'img_height' => 200,
        'img_product_width' => 500,
        'img_product_height' => 500,
        'img_menu_width' => 150,
        'img_menu_height' => 150,
        'img_slider_width' => 1920,
        'img_slider_height' => 900,
        'img_blog_width' => 240,
        'img_blog_height' => 322,
    ];
